version: '3'

services:
  mariadb:
    image: mariadb:10.5.5
    restart: always
    ports:
      - "${MARIADB_BIND_IP_PORT:-127.0.0.1:3306}:3306"
    volumes:
      - ./mariadb/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "concert"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"

  cassandra:
    build:
      context: cassandra
    ports:
      - "${CASSANDRA_IP_PORT:-127.0.0.1:9042}:9042"
    environment:
      MAX_HEAP_SIZE: ${CASSANDRA_MAX_HEAP_SIZE:-256M}
      HEAP_NEWSIZE: ${CASSANDRA_HEAP_NEWSIZE:-128M}
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 3s
      timeout: 2s
      retries: 60
