create table `CONCERTS` (
    `ID` VARCHAR(512) NOT NULL PRIMARY KEY,
    `NUMBER_OF_TICKETS` INTEGER NOT NULL,
    `CANCELLED` BOOLEAN NOT NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `UPDATED_AT` DATETIME NOT NULL
);

create table `UPDATER_OFFSETS` (
    `TAG_NAME` VARCHAR(64) NOT NULL PRIMARY KEY,
    `OFFSET_UUID` CHAR(36) NOT NULL
);
