name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main, feature/** ]

env:
  lerna.enable.discipline: true

jobs:
  test:

    runs-on: ubuntu-latest

    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html#Caching
      - name: Coursier cache
        uses: coursier/cache-action@v5

      - name: Check code format
        run: sbt scalafmtSbtCheck scalafmtCheckAll

      - name: Run tests
        run: sbt clean test:compile testAll

        # https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html#Caching
      - name: Clean files for caching
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
